version: 2
updates:
- package-ecosystem: gradle
  directory: /
  schedule:
    interval: daily
  groups:
    default:
      patterns:
      - '*'
  labels:
  - dependencies
  - auto-merge
  - dependabot
  - cleanup
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  labels:
  - actions-dependencies
  - auto-merge
  - dependabot
  - cleanup
