name: Gradle Build (on pull)
'on':
  pull_request:
    branches:
    - main
    types:
    - opened
    - reopened
    - synchronize
jobs:
  build_datakache:
    runs-on: ubuntu-latest
    if: ${{ !contains(join(github.event.pull_request.labels.*.name, ','), 'actions-dependencies')
      }}
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: temurin
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96
      with:
        gradle-version: current
    - name: Build with Gradle
      run: gradle build
